# fly.toml app configuration file generated for morgenassistent on 2025-05-10T08:11:51Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'morgenassistent'
primary_region = 'fra'

[build]

[processes]
  app = "python main.py"  # ← wichtig für Background Worker

[experimental]
  auto_rollback = true

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[mounts]
  source = "data"
  destination = "/data"
